[tool.poetry]
name = "welleng"
version = "0.7.3"
description = "A collection of Well Engineering tools"
authors = ["Jonathan Corcutt <jonnycorcutt@gmail.com>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.2"
scipy = "^1.10.1"
Pint = "^0.20.1"
PyYAML = "^6.0"
vtk = "^9.2.6"
magnetic-field-calculator = {version="^1.0.2", optional=true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
