[tool.poetry]
name = "welleng"
version = "0.7.3"
description = "A collection of Well Engineering tools"
authors = ["Jonathan Corcutt <jonnycorcutt@gmail.com>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.2"
scipy = "^1.10.1"
Pint = "^0.20.1"
PyYAML = "^6.0"
vtk = "^9.2.6"
magnetic-field-calculator = {version="^1.0.2", extras=["easy", "all"]}
networkx = {version="^3.0", extras=["easy", "all"]}
numba = {version="^0.56.4", extras=["all"]}
openpyxl = {version="^3.1.2", extras=["easy", "all"]}
pandas = {version="^1.5.3", extras=["easy", "all"]}
tabulate = {version="^0.9.0", extras=["easy", "all"]}
trimesh = {version="^3.21.3", extras=["easy", "all"]}
utm = {version="^0.7.0", extras=["easy", "all"]}
vedo = {version="^2023.4.4", extras=["easy", "all"]}
python-fcl = {version="^0.7.0", extras=["all"]}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
